WITH RECURSIVE JER (LEVEL, DATABASENAME, OWNERNAME, ROUTE)
AS
(
SELECT 1 LEVEL,
       DATABASENAME,
       OWNERNAME,
       CAST('C:/'||TRIM(DATABASENAME) AS VARCHAR(128)) ROUTE
  FROM DBC.DATABASES
 WHERE DATABASENAME= 'gcfr_main'
UNION ALL
SELECT JER.LEVEL + 1,
       D.DATABASENAME,
       D.OWNERNAME,
       JER.ROUTE || '/' || TRIM(D.DATABASENAME)  
  FROM DBC.DATABASES D,
       JER
 WHERE d.DATABASENAME<> 'gcfr_main'
   AND d.OWNERNAME = JER.DATABASENAME
   AND DBKind = 'D'
)
SELECT LEVEL, 
       DATABASENAME, 
       OWNERNAME, 
       ROUTE
  FROM JER
 ORDER BY 4